### ISSUE TITLE
Assignment 6-3 - Blog Tags

### ISSUE THREAD

**Issue by ambethia** [utumno86/Assignments#29]
# Week 6 - Day 2

We're going to continue making a blog app.

- [x] Create a `Tag` model, it will probably have a `name`.
- [x] Create a `Tagging` model, it will have post and tag references.
- [x] Setup the many-to-many relationship between `Post` and `Tag`
- [x] The user should be able to add tags to a post when editing it (can be done a few ways, google will help you here, see how others solve this very same common problem)
- [x] The visitor facing post page should show a list of tags that a post was tagged with.
- [ ] *Bonus*: Make the listed tags from the previous feature link to a list of blog posts that have that tag.

**Comment by utumno86** [comment]
https://github.com/utumno86/bloggertron
This is literally the most lackluster possible version of the assignment requirements, but it fulfills them, and I gots TODOS to work on.

**Comment by utumno86** [comment]
Oops, forgot to add an edit function.

**Comment by utumno86** [comment]
Okay, now it's ready

**Comment by ambethia** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/55jOowTAknOXC/200w_d.gif)
