### ISSUE TITLE
Assignment 7-3 - Blog - Ajax Comments

### ISSUE THREAD

**Issue by ambethia** [utumno86/Assignments#33]
# Week 7 - Assignment 3

## jQuery Ajax

We're going to add commenting with AJAX to our blog posts. You'll need to do a fair bit of reading and research on jQuery and javascript to build on what we demoed in class. Try using some of the terminology in the requirements here as search keywords to guide you. This research is primary component of this assignment. You'll really only end up writing a few lines of code to get this done.

## Requirement

- [x] Remember about `$(function { '...' })` to wait for the DOM to be ready.
- [x] Catch the `submit` event on your comment form. Look into `event.preventDefault()` to stop it from actually submitting, and do an AJAX request to `comments#create` instead.
- [x] Have your create action respond to both HTML and JSON
- [x] The JSON response should render a partial for a single comment into a string 
- [x] Your AJAX `success` handler should take the response data (your comment partial) and `append` it to the comments list.
- [x] BAM AJAX!

**Comment by utumno86** [comment]
https://github.com/utumno86/bloggertron

**Comment by ambethia** [comment]
Is this broken in your last deploy? it doesn't seem to work.

**Comment by utumno86** [comment]
I definitely saw it work once (in development, not on Heroku) but it may have only worked for like 5 minutes on a Tuesday morning. I'll try to get it working again.

**Comment by utumno86** [comment]
You saw this actually work that one time right? It happens kind of sporadically.

**Comment by utumno86** [comment]
https://bloggertron.herokuapp.com
