### ISSUE TITLE
Assignment 9-4 - Teamwork

### ISSUE THREAD

**Issue by ambethia** [utumno86/Assignments#42]
# Week 9 - Assignment 4

## Working as a Team

- [x] With your 3 other team members: deploy an app you can be proud of. Push it harder and further than projects up until now.

| Red Team | Blue Team |
|----------|-----------|
| Michael  | Derek     |
| Kelly    | Josh      |
| Aaron    | Amie      |
| Duncan   | Bennett   |

**Comment by utumno86** [comment]
Don't know whether others in the group want to continue adding features, but I am done for my part. https://github.com/utumno86/twixter https://twixter.herokuapp.com/
